name: Build Docker Containers

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".gitignore"
  workflow_dispatch:

jobs:

  build-alpine:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Alpine Dockerfile
        id: docker_build
        uses: docker/build-push-action@v3.2.0
        with:
          platforms: linux/arm64,linux/armhf,linux/386,linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:alpine
          pull: false
          context: .
          file: Dockerfile

  build-debian:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Debian Dockerfile
        id: docker_build
        uses: docker/build-push-action@v3.2.0
        with:
          platforms: linux/arm64,linux/armhf,linux/386,linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:debian
          pull: false
          context: .
          file: Debian_Dockerfile
